### ISSUE TITLE
Recent update breaks color highlighting in SCSS

### ISSUE THREAD

**Issue by erindotio** [Monnoroch/ColorHighlighter#238]
Something happened in the last day or two where the color highlighting looks completely broken now in SCSS files:

![image](https://cloud.githubusercontent.com/assets/1291167/9401211/bb440d8a-4780-11e5-986e-6dd980a8f996.png)

**Comment by woble** [comment]
Similar issue in LESS as well.

**Comment by Monnoroch** [comment]
Fixed!

**Comment by erindotio** [comment]
Thank you!

**Comment by voltronik** [comment]
I'm still getting this in the latest version. I installed the package from scratch today.

**Comment by Monnoroch** [comment]
Could you make screenshot as well?

**Comment by voltronik** [comment]
Sure. See here:  https://www.dropbox.com/s/ek4zpt1553bbh1i/Screenshot%202015-08-26%2005.29.39.png?dl=0

**Comment by woble** [comment]
Same issue here as well. Looks like variables from other files aren't recognized.
![](http://i.imgur.com/Qa6oKYi.png)

**Comment by voltronik** [comment]
That's actually what i'm experiencing too - it's working for my main variables.scss file but not for my other Sass files.

**Comment by Monnoroch** [comment]
I have explained this a hundred times already: either you @import the file with variables definition, or you put that file into a project settimg (see readme). I can't magically understand which files have variables for which other files.

**Comment by woble** [comment]
Always using @import to import variables, albeit a single file that imports both variables and mixin files. It worked just fine all the time. After recent updates it worked only once and then stopped. Importing just the variables file doesn't solve the issue either.

![](http://i.imgur.com/I1cr7E2.png)

**Comment by Monnoroch** [comment]
Cannot reproduce, sorry.

![f](https://cloud.githubusercontent.com/assets/1500400/9578815/c51b2884-4ff5-11e5-83fa-fa4915f13b9a.png)

**Comment by woble** [comment]
Great, thanks.
